Repository RedHatCRE/cibyl, pull requests merged in 2022-03, with the labels that each got.

#91 Fix systems argument duplication
  cibyl/cli/validator.py
  cibyl/exceptions/model.py
  cibyl/models/ci/system.py
  tests/cli/test_validator.py
Labels: bug

#85 Use pylintrc according to Google Python Style Guide
  .pylintrc
  cibyl/cli/main.py
  cibyl/sources/elasticsearch/api.py
  docs/source/contribute.rst
  tests/sources/elasticsearch/test_api.py
  tests/sources/test_jenkins.py
Labels: styling

#90 Introduce quiet exceptions
  cibyl/cli/main.py
  cibyl/exceptions/__init__.py
  cibyl/exceptions/config.py
  cibyl/exceptions/elasticsearch.py
  cibyl/exceptions/jenkins.py
  cibyl/exceptions/jenkins_job_builder.py
  cibyl/exceptions/model.py
  cibyl/exceptions/source.py
Labels: Improvement

#98 Creating e2e testing environment and a sample of how a test would look like.
  e2e/__init__.py
  e2e/configs/jenkins.yaml
  e2e/images/jenkins/Dockerfile
  e2e/images/jenkins/setup.yaml
  e2e/test_jenkins.py
  tox.ini
Labels: tests

#101 Remove get_last_build func from --last-build
  cibyl/models/ci/build.py
  cibyl/models/ci/job.py
  cibyl/sources/jenkins.py
Labels: Models

#103 Allow model attributes outside init dictionary
  cibyl/models/model.py
Labels: bug, Core

#99 Add a QueriesCache class to avoid repeating calls
  cibyl/orchestrator.py
  cibyl/utils/source_methods_store.py
  tests/utils/test_source_metdhods_store.py
Labels: Core

#116 Add models documentation
  docs/source/models/core.rst
  docs/source/models/plugin.rst
  docs/source/plugins/openstack.rst
Labels: Docs
